/*
Deployment script for C:\USERS\S-CEVIK\SOURCE\REPOS\WEBAPPLICATION1\WEBAPPLICATION1\APP_DATA\SAGLIKDB.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\USERS\S-CEVIK\SOURCE\REPOS\WEBAPPLICATION1\WEBAPPLICATION1\APP_DATA\SAGLIKDB.MDF"
:setvar DefaultFilePrefix "C_\USERS\S-CEVIK\SOURCE\REPOS\WEBAPPLICATION1\WEBAPPLICATION1\APP_DATA\SAGLIKDB.MDF_"
:setvar DefaultDataPath "C:\Users\s-cevik\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\s-cevik\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Update complete.';


GO
SELECT TOP 1000 [MedicineId],
				[MedicineName],
				[MedicineUnit],
				[MedicineCount],
				[MedicineDate]
				FROM [dbo].[MedicineTable]