//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    public partial class MedicineTable
    {
        public int MedicineId { get; set; }
        public string MedicineName { get; set; }
        public string MedicineUnit { get; set; }
        public int MedicineCount { get; set; }
        public System.DateTime MedicineDate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
